### ISSUE TITLE
Integrate GenServer/TaskSupervisor into Code to deprecate sequential run_pipeline function 

### ISSUE THREAD

**Issue by samrose** [samrose/ex_integrate#25]

**Comment by garrettmichaelgeorge** [comment]
This depends on #28 (RunManager) and #22 (halting a run if a step fails). Cf. https://github.com/samrose/ex_integrate/pull/21#discussion_r770734608 and https://github.com/samrose/ex_integrate/pull/21#issuecomment-996004033.

**Comment by garrettmichaelgeorge** [comment]
The goal is to
* make it so that the top-level `ExIntegrate` API utilizes the concurrent OTP application for managing a run, rather than the initial sequential implementation.

* to remove this deprecated function: https://github.com/samrose/ex_integrate/blob/bb202a086f1193583afe7c8004c052b1adf03061/lib/ex_integrate/pipeline_runner.ex#L75-L90
